-- Rewrite seeded descriptions without em dashes. Only rows still holding the original seeded text are changed,
-- so descriptions edited in the admin panel are left alone.
UPDATE "PropertyType" SET "description" = 'Houses are the most searched rental category in Lahore. Sizes are usually quoted in Marla or Kanal. 5 and 10 Marla homes suit smaller families, while 1 Kanal and larger homes offer extra bedrooms, lawns and servant quarters. Compare monthly rent, security deposit and advance terms before shortlisting.' WHERE "slug" = 'house' AND "description" = 'Houses are the most searched rental category in Lahore. Sizes are usually quoted in Marla or Kanal — 5 and 10 Marla homes suit smaller families, while 1 Kanal and larger homes offer extra bedrooms, lawns and servant quarters. Compare monthly rent, security deposit and advance terms before shortlisting.';
UPDATE "PropertyType" SET "description" = 'A lower portion is the ground floor of a house rented separately. Tenants often get easier access, a car porch and sometimes a lawn, which suits families with elderly members or young children.' WHERE "slug" = 'lower-portion' AND "description" = 'A lower portion is the ground floor of a house rented separately. Tenants often get easier access, a car porch and sometimes a lawn — a good fit for families with elderly members or young children.';
UPDATE "PropertyType" SET "description" = 'Hostels and paying-guest (PG) accommodation for students and working professionals. Rooms are shared or single, with meals, laundry and security often included in one monthly charge.' WHERE "slug" = 'hostel' AND "description" = 'Hostels and paying-guest (PG) accommodation for students and working professionals — shared or single rooms with meals, laundry and security often included in one monthly charge.';
UPDATE "PropertyType" SET "description" = 'Showrooms offer wide frontage and large display floors on busy commercial roads and suit car dealers, furniture, apparel and electronics retailers.' WHERE "slug" = 'showroom' AND "description" = 'Showrooms offer wide frontage and large display floors on busy commercial roads — suited to car dealers, furniture, apparel and electronics retailers.';
UPDATE "PropertyType" SET "description" = 'Industrial spaces (open plots with sheds, yards and workshops) are rented for manufacturing, storage and fabrication work on Lahore''s outskirts.' WHERE "slug" = 'industrial-space' AND "description" = 'Industrial spaces — open plots with sheds, yards and workshops — are rented for manufacturing, storage and fabrication work on Lahore''s outskirts.';
UPDATE "Location" SET "description" = 'Bahria Town Lahore is a gated private housing society in the south-west of the city with its own commercial areas, schools, hospital and parks. It offers a wide mix of rentals, from apartments above commercial blocks and 5 to 10 Marla houses to larger homes and shops, and is popular with families looking for a self-contained community.' WHERE "slug" = 'bahria-town' AND "description" = 'Bahria Town Lahore is a gated private housing society in the south-west of the city with its own commercial areas, schools, hospital and parks. It offers a wide mix of rentals — apartments above commercial blocks, 5 to 10 Marla houses, larger homes and shops — and is popular with families looking for a self-contained community.';
UPDATE "Location" SET "description" = 'Johar Town is a large, well-connected residential and commercial area in south-west Lahore, close to the Expo Centre, Emporium Mall and several universities and hospitals. It has one of the city''s widest ranges of rental stock, including houses, portions, flats, rooms, offices and shops, which makes it a common choice for students, professionals and families.' WHERE "slug" = 'johar-town' AND "description" = 'Johar Town is a large, well-connected residential and commercial area in south-west Lahore, close to the Expo Centre, Emporium Mall and several universities and hospitals. It has one of the city''s widest ranges of rental stock — houses, portions, flats, rooms, offices and shops — which makes it a common choice for students, professionals and families.';

-- Demo records and generated photo captions used " — " as a separator.
UPDATE "PropertyImage" SET "alt" = replace("alt", ' — ', ', ') WHERE "alt" LIKE '% — %';
UPDATE "Agent" SET "agency" = replace("agency", ' — Demo Agency', ' (Demo Agency)') WHERE "agency" LIKE '% — Demo Agency';
UPDATE "Property" SET "description" = replace("description", 'DEMO LISTING — this sample record', 'DEMO LISTING: this sample record') WHERE "isDemo" = true AND "description" LIKE 'DEMO LISTING — %';
